### PR TITLE
Handle metrics that has no filepath

### PR DESCRIPTION
**Pull request by chuanlin2018**
Issue: landing page crashed when metrics data didn't have filepath info.
Example: https://testdata.nist.gov/od/id/66AF4AFEA96764C4E0532457068100261895
Fix: Check filepath attribute before using it.
Testing: To test using testdata.nist.gov as backend, in environment.ts set useMetadataService: true, useCustomizationService: true and replace data.nist.gov with testdata.nist.gov. 
Test samples:
http://localhost:4200/metrics/mds2-2124
http://localhost:4200/lps/mds2-2124
http://localhost:4200/metrics/576CE869311197F3E0531A570681C5C71857
http://localhost:4200/lps/576CE869311197F3E0531A570681C5C71857

### CODE REVIEW

**Comment by RayPlante** [comment]
This PR has some conflicts with #320 .  Can you try resolving them?  (Try merging the two branches together to see the conflicts.)

**Comment by chuanlin2018** [comment]
Will do.

**Comment by chuanlin2018** [comment]
Fixed. Sorry for the delay. It took me a while to figure out what had been changed in both PRs...

**Review by RayPlante — APPROVED** [review]
Conflicts are resolved.  Behavior tested and confirmed on testdata.

**Pull request merged**
