### PR TITLE
Handled missing pdrid in metrics

### PR DESCRIPTION
**Pull request by chuanlin2018**
Issue: https://sgitlab.nist.gov/oar-odd/landing-page-service/-/issues/3
Landing page crashed because there was no pdrid in metrics data.

Fix: Added pdrid check in getMetrics() in both landingpage and metrics component.

### CODE REVIEW

**Review by RayPlante — COMMENTED** [review]
I tested this locally by ingesting a new record and then editing its record in recordMetrics to  remove the `pdrid` property.  I confirmed the error with the unpatched version of the app and then confirmed the fix with the patch from this PR.  

Just waiting on the remaining updates

**Comment by chuanlin2018** [comment]
Just checked the fix for metrics page. Still working on landing page side... There are similar code in both page that need be put in a service but will work on it later.

**Comment by chuanlin2018** [comment]
All fixed.

**Comment by chuanlin2018** [comment]
In metrics page I moved file level metrics code inside record level metrics function because if there is no metrics level data, no need to fetch file level data.

**Comment by chuanlin2018** [comment]
Loading metrics data after Nerdm record loaded.

**Review by RayPlante — APPROVED** [review]
Tested locally again; no issues found.

**Comment by RayPlante** [comment]
Checked on testdata; no issues.  Merging.

**Pull request merged**
