### PR TITLE
ODD-940:  Data Cart code restructuring

### PR DESCRIPTION
**Pull request by chuanlin2018**
This PR basically do the code restructure of data cart. The data cart page was split into three parts: cart controls, bundle plan and tree table. A new datacart class was created and most of cart related functions were moved from cart services into datacart class.

This PR changed the download all behavior - instead of popping up a new data cart window, now creating a new tab. 

This PR fixed the status sync between tabs - 
1. When files added to the cart in the landing page, they automatically showed up in the global data cart page if it's opened already (without refreshing the page). 
2. Any file downloaded in data cart page, the status in the landing page will be updated automatically  (without refreshing the page). 

This PR also added a new feature: display bundle download progress in the landing page. There will be one progress bar for each data cart (global data cart, download all data carts). Each progress bar can be manually closed once the download is completed or the tab is closed. The title of the progress bar is either "Global Data Cart" or the first 20 characters of the collection title.

To test, download the branch and run it in local docker as usual.

### CODE REVIEW

**Comment by RayPlante** [comment]
I did a rebase with integration (instead of a merge of integration) which is why the change history looks funny.  I'm not sure this was a good idea.

**Review by RayPlante — CHANGES_REQUESTED** [review]
Overall, this code looks very good and accomplishes the goals set out in ODD-940, particularly with providing better encapsulation of the cart activities.  

There is a server-side rendering issue that needs to be fixed.  Testing under oar-docker, the server-side log (data/logs/pub-pdr/lps.log) had the following error message causing server-side rendering to fail:
```
LPS Application Error: ReferenceError: localStorage is not defined
ReferenceError: localStorage is not defined
    at Function../src/app/datacart/cart.ts.DataCart.openCart (/var/www/html/dist/server.js:137790:33)
    at DataFilesComponent../src/app/landing/data-files/data-files.component.ts.DataFilesComponent.updateStatusFromCart (/var/www/html/dist/server.js:142571:51)
    at DataFilesComponent../src/app/landing/data-files/data-files.component.ts.DataFilesComponent.buildTree (/var/www/html/dist/server.js:142499:14)
    at DataFilesComponent../src/app/landing/data-files/data-files.component.ts.DataFilesComponent.ngOnChanges (/var/www/html/dist/server.js:142475:14)
    at checkAndUpdateDirectiveInline (/var/www/html/dist/server.js:23467:19)
    at checkAndUpdateNodeInline (/var/www/html/dist/server.js:24735:20)
    at checkAndUpdateNode (/var/www/html/dist/server.js:24697:16)
    at prodCheckAndUpdateNode (/var/www/html/dist/server.js:25238:5)
    at Object.updateDirectives (/var/www/html/dist/server.js:146032:8009)
    at Object.updateDirectives (/var/www/html/dist/server.js:25026:72)
Setting response status to 500
```
Obviously, the `inBrowser` guard needs to be applied to the part of the landing page display that interacts with the cart.

**Comment by chuanlin2018** [comment]
The fix foe server-side error checked in. Please check again.

By the way, I wiped out local oar-docker folder and re-clone the integration branch and updated the tag name of pubpdr to fix/ODD940-clean-up. The build still faile:

...
make  tests/man.test
make[3]: Entering directory '/root/jq-dev'
Changes to the manual.yml require docs to be enabled to run the tests
Makefile:1839: recipe for target 'tests/man.test' failed
make[3]: Leaving directory '/root/jq-dev'
make[3]: *** [tests/man.test] Error 1
make[2]: *** [check-am] Error 2
Makefile:1644: recipe for target 'check-am' failed
make[2]: Leaving directory '/root/jq-dev'
Makefile:1151: recipe for target 'check-recursive' failed
make[1]: Leaving directory '/root/jq-dev'
make[1]: *** [check-recursive] Error 1
Makefile:1647: recipe for target 'check' failed
make: *** [check] Error 2
ERROR: Service 'nerdmbase' failed to build: The command '/bin/sh -c git clone http://github.com/stedolan/jq.git jq-dev &&     cd jq-dev &&     git checkout 6306ac89667cf35f47ddc40aa0630546c57e387f &&     git submodule update --init &&     autoreconf -fi &&     ./configure --prefix=/usr/local --with-oniguruma=builtin &&     make -j8 &&     make check &&     make install' returned a non-zero code: 2

**Comment by chuanlin2018** [comment]
getDialogWidth() now returns a default value if inBrowser=false.

**Comment by RayPlante** [comment]
@chuanlin2018 BTW, can you fix these conflicts?

**Comment by chuanlin2018** [comment]
Just want to make sure I did it right:
 
1. Switch to integration branch and do git pull
2. git merge fix/ODD940-clean-up
3. Resolve conflicts in Visual Studio Code
4. Run ./scripts/makedist
5. Run ./scripts/testall
 
Now should I
    Push to usnistgov/integration ?

**Comment by chuanlin2018** [comment]
Followed your instruction. It failed at following step:

lnc9$ git merge --continue
fatal: There is no merge in progress (MERGE_HEAD missing).

When I started over it seemed everything was up to date. So I just go ahead push the fix to usnistgov.
Please check.
Thanks.

**Comment by RayPlante** [comment]
I was going from memory just before heading into a meeting, so I was a little fuzzy on that step.  However, the messages that appear when the merge fails due to conflicts are pretty clear about what to do next (as are the messages when you then run "git status").

The PR now says we are clear of conflicts; now just waiting on Travis.  Thanks!

Ray

**Comment by chuanlin2018** [comment]
Great!

**Review by RayPlante — APPROVED** [review]

**Pull request merged**
