### PR TITLE
Added nerdm document link

### PR DESCRIPTION
**Pull request by chuanlin2018**
http://mml.nist.gov:8080/browse/ODD-1014

Added NERDm document link to 'About this dataset' section. It links to https://data.nist.gov/dm/nerdm/.

### CODE REVIEW

**Review by RayPlante — CHANGES_REQUESTED** [review]
The NERDm doc link needs to be provided in a platform-independent so that when on test, it points to testdata.nist.gov, etc.  The pdr-lps configuration includes a "nerdmAbout" parameter that provides the platform-specific link; so you should be able to have `AboutDatasetComponent` consult the `AppConfig` for this link.

**Comment by RayPlante** [comment]
Also, BTW, the proper URL is `.../od/dm/aboutNerdm.html`; this is set as the default value in `AppConfig`.

**Comment by chuanlin2018** [comment]
Tested in local.

**Comment by RayPlante** [comment]
Looks like a small change is needed to `config.spec.ts`; see https://github.com/usnistgov/oar-pdr/runs/4120583005?check_suite_focus=true

**Comment by chuanlin2018** [comment]
Ah, forgot to check in...

**Review by RayPlante — APPROVED** [review]
All good.

**Pull request merged**
