### PR TITLE
ODD-750-747: Improve error handling; fixed footer ext link icon

### PR DESCRIPTION
**Pull request by chuanlin2018**
Jira ticket: 
http://mml.nist.gov:8080/browse/ODD-750
http://mml.nist.gov:8080/browse/ODD-747

1. Fixed the status display of datacart direct download while server side returns error
2. Changed "Please try again" to "Please email us" with the email link in bundle download
3. Fixed ext link in PDR footer (ODD-747)
4. Some code clean up

makedist worked fine. Local deployment got error in oar-rmm. I believe it's tag problem. Will get the right one tomorrow and re-run.

### CODE REVIEW

**Comment by chuanlin2018** [comment]
"Fixed bundle download error handling" - fixed the problem that when one bundle got an error the download manager won't kick off next bundle. Also display more info when download failed. Tested with mock data but not in local deploy because bundle plan failed to response. scripts/makedist ran successful. Can this be deployed to testdata?

**Comment by chuanlin2018** [comment]
"Fixed bundle download error handling" - fixed the problem that when one bundle got an error the download manager won't kick off next bundle. Also display more info when download failed. Tested with mock data but not in local deploy because bundle plan failed to response. scripts/makedist ran successful. Can this be deployed to testdata?

**Comment by RayPlante** [comment]
I cleared out my cart and tried it again and was not able to replicate it.  Maybe it was a caching issue after all.  I'll keep testing.

**Comment by RayPlante** [comment]
I'm calling this all-clear.

**Comment by chuanlin2018** [comment]
Great!

**Pull request merged**
