### PR TITLE
ODD-861 Fix bundle download error handling

### PR DESCRIPTION
**Pull request by chuanlin2018**
http://mml.nist.gov:8080/browse/ODD-861

This check in is to fix the error handling of bundle downloading. Current version does not display details returned from bundle plan and error massage does not contains any detail info.

Here are the changes:

1. Added background image to "Download Manager" title bar and placed the control buttons in the title bar;
2. Removed the top error message line and the detail error message table;
3. Placed tech support contact at the right side of the message header. When user click on the email link, email client will pop up with error message in certain format that we discussed;
4. In the file tree table, placed the download icons in a new "Action" column. The icon will blinking if the file is been downloading.
5. In the file tree table, if a file is been downloading, a spinner will appear to the left of the status "downloading". if any file failed to download, the status "failed" will be clickable. When user clicks on it, it will pop up a window with detail info: file path, url and message.
6. In the file tree table, changed "Status reset" button from one single little icon to "reset" and placed it to the right of the status header column.

[05/08/2020] updates:

1. Move the action column before “Media Type”
2. For single file download update text in tooltip to “Download this file”
3. Update status with icon matching same color as text

===
Tested in local oar-docker. Test cases:

JANAF (Not downloadable. Should return error)
ECBCC1C1301D2ED9E04306570681B10735

Quantum dot data (Downloadable)
66492819760D3FF6E05324570681BA721894

Here is oar-docker config:

_app:
  app_dir:   .
ingestdata:
  service_root: rmm/ingestdata
  components:
    - name: pdr-nerdm
      repo:
        owner:  usnistgov
        name:   oar-metadata
        tag:    1.0.10
      deploy:
        method: copy
ingestservice:
  service_root: rmm/ingestservice
  components:
    - name: pdr-nerdm
      repo:
        owner:  usnistgov
        name:   oar-metadata
        tag:    1.0.10
      deploy:
        method: copy
rmmapi:
  service_root: rmm/restapi
  components:
    - name: oar-rmm-service
      repo:
        owner:  usnistgov
        name:   oar-rmm
        tag:    1.0.2
      deploy:
        destination: app
        method:      copy
pubpdr:
  service_root: pub-pdr
  components:
    - name: pdr-lps
      repo:
        owner:  usnistgov
        name:   oar-pdr
        tag:    fix/ODD861-bundle-download-error-handle
      deploy:
        destination: builtpdr
        method:      unzip
sdp:
  service_root: sdp
  components:
    - name: sdp
      repo:
        owner: usnistgov
        name:  oar-sdp
        tag:   1.2.4rc2
      deploy:
        destination: builtsdp
distservice:
  service_root: dist-service
  components:
    - name: oar-dist-service
      repo:
        owner:  usnistgov
        name:   oar-dist-service
        tag:    2.1.6
configserver:
  service_root: ../configs/config-server
  components:
    - name: oar-config-server
      repo:
        owner:  usnistgov
        name:   oar-config
        tag:    1.0.12rc4
nginxreverseproxy:
  service_root: nginx-reverse-proxy
  components:
    - name: nerdm-docs
      repo:
        owner:  usnistgov
        name:   oar-metadata
        tag:    1.0.8
      deploy:
        method: copy

### CODE REVIEW

**Comment by RayPlante** [comment]
@chuanlin2018 Please test this under oar-docker--that's where it counts at the end of the day.  

I would recommend the following process:
1. Add some files from the JANAF dataset and some from the "Quantum dot data" dataset to your datacart
2. First select files from the JANAF dataset in the data cart and attempt a download.  None of these will download, no zips can be created.  Is the messaging as you expect?
3. Now select files from both datasets.  Since the quantum dot data is downloadable, you should be able to create at least one zip with those files.  Is the messaging as you expect for this case?

**Comment by chuanlin2018** [comment]
Will do.

**Comment by chuanlin2018** [comment]
Assume I still use feature/ODD-774-customization-api branch...

**Comment by RayPlante** [comment]
If the branch for this PR was derived from oar-pdr `integration` (which I believe is true), then you should use the `integration` (or `rel/1.3.X`) oar-docker branch.

**Comment by chuanlin2018** [comment]
Ah ok. feature/ODD-774-customization-api is for new workflow, correct?

**Comment by RayPlante** [comment]
> feature/ODD-774-customization-api is for new workflow, correct?
Correct!

**Comment by chuanlin2018** [comment]
Made following changes:

The help button next to the three control buttons now has content in it,
Service side error was fixed,
Used “theme” field for topic instead of “topics” field
Fixed the big white space when server side return 404

**Comment by deoyani** [comment]
@chuanlin 

These last changes you mentioned are related to customization, this is download Error related branch. Are you using same branch for both?

**Comment by chuanlin2018** [comment]
Sorry, I copied wrong text. Should be these changes:

1. Move the action column before “Media Type”
2. For single file download update text in tooltip to “Download this file”
3. Update status with icon matching same color as text

**Comment by deoyani** [comment]
Ok sounds good. I tested locally works as expected.

**Pull request merged**
