### PR TITLE
Fix/metrics performance

### PR DESCRIPTION
**Pull request by chuanlin2018**
This version fixed following issues. It also included the change in PR#255 (keyword filter dropdown display nothing when user removed one selected keyword)

1. Fixed metrics info display: display spinner at right side of the green title bar before metrics data is ready.
2. Fixed the font in metrics info: defined the font family in style.scss to make it global. Set the font size locally.
3. Fixed "Visit Home Page" button color: I realized that it displayed science theme color all the time.
4. Made keyword suggestion list case-insensitive.
5. Display spinner in the search result section while loading: current version displayed "0 dataset found" first, then the number was updated.

### CODE REVIEW

**Comment by deoyani** [comment]
@chuanlin2018 I tested all the changes except the metrics spinner etc, it is not obvious to me, can you confirm whether metrics API is called ? I do not see in the network calls in javascript console. Try using 8C401B5C708647B8E05324570681610A2081 as it has the data for metrics in oardev.

**Comment by chuanlin2018** [comment]
Let me check.

**Comment by chuanlin2018** [comment]
This is the url to get metrics data:
https://oardev.nist.gov/rmm/usagemetrics/files?exclude=_id&include=ediid,filepath,success_get,download_size&ediid=8C401B5C708647B8E05324570681610A2081

**Comment by chuanlin2018** [comment]
I just ran it locally and I realized that line 206 in styles.scss need be commented out in order to see the spinner. I will check in the fix soon:
Screen Shot 2022-06-06 at 11 23 28 AM

**Comment by deoyani** [comment]
> This is the url to get metrics data:
> https://oardev.nist.gov/rmm/usagemetrics/files?exclude=_id&include=ediid,filepath,success_get,download_size&ediid=8C401B5C708647B8E05324570681610A2081

Thats right but it does not seem to get called when I was testing this branch locally.

**Comment by chuanlin2018** [comment]
The link was copied from console log. I added a console log right before the url was called...

**Comment by chuanlin2018** [comment]
Just checked in the fix to the spinner css.

**Comment by chuanlin2018** [comment]
It failed again in Python tests:
Screen Shot 2022-06-07 at 2 14 50 PM
I am not sure how to fix it except restart the process...

**Comment by RayPlante** [comment]
It looks like we may have it an docker hub access limit; we may need to wait until tomorrow to rerun

**Comment by RayPlante** [comment]
All tests have now passed.

**Comment by deoyani** [comment]
Everything works! Metrics spinner needs testing on the server.

**Pull request merged**
