### PR TITLE
Removed the space before comma in author list and research topic; Tre…

### PR DESCRIPTION
**Pull request by chuanlin2018**
…at semicolon as comma in keywords.

This is a quick fix. No Jira tickets for this.

This fix removed the space before each comma in the author and research topic list. Also treat semicolon the same as comma to avoid long keywords from some records.

To test it locally, set useMetadataService: false, then browse http://localhost:4200/lps/test0. It will display mds2-2497.

### CODE REVIEW

**Review by RayPlante — APPROVED** [review]
Tested under oar-docker, locally.  The fixes that are part of this PR worked; however, the comma issue exists for listing authors in the citations.

**Comment by chuanlin2018** [comment]
I didn't fix citations. Will try to fix it by 5pm. Otherwise will be done later this evening.

**Comment by chuanlin2018** [comment]
Are you talking about this pop up? I didn't see the problem...
Screen Shot 2022-08-23 at 4 51 18 PM

**Comment by RayPlante** [comment]
Look at a record where multiple authors have been defined, e.g. https://oardev.nist.gov/od/id/ark:/88434/mds2-2516

**Comment by chuanlin2018** [comment]
Ok I need to take my mom to an appointment now. Will work on it after I come back.

**Comment by RayPlante** [comment]
no rush

**Comment by chuanlin2018** [comment]
Fixed.

**Pull request merged**
