### PR TITLE
508 compliance

### PR DESCRIPTION
**Pull request by chuanlin2018**
http://mml.nist.gov:8080/browse/ODD-792

Changes to color and button labels for 508 compliance.
Based on integration13.

### CODE REVIEW

**Comment by RayPlante** [comment]
@chuanlin2018 please resolve this conflict.

**Comment by chuanlin2018** [comment]
Resolved. I saw you changed "integration13" to "integration". So "integration" is now restructured code.

**Comment by RayPlante** [comment]
Did you really mean to choose pink here?
Spectacle z30096

**Comment by RayPlante** [comment]
To answer my own question, I guess the answer is, yes, from looking at the file.  I applaud you for your boldness, but I think we need a different color here.  What is the recommendation this color change is addressing?

**Comment by chuanlin2018** [comment]
In light background, a visited link is usually in dark pink color. So for dark background, I need to change it to lighter color for 508 compliance. I don't like this color either. Let's discuss in the standup meeting to pick a different color.

**Comment by RayPlante** [comment]
Do we need to set a visited color?  Can we just keep it white?

**Comment by chuanlin2018** [comment]
Sure. That's a good option.

**Comment by RayPlante** [comment]
Cool.  Let's go with that.  Thanks!

**Comment by chuanlin2018** [comment]
I like your idea. Actually a menu item should always be the same color. Will check in the change soon.

**Comment by RayPlante** [comment]
FYI, I tested both under apps and publish as well as with editing enabled.

**Comment by chuanlin2018** [comment]
Great. I tested in local oar-docker and everything appeared to be working fine.

**Pull request merged**
