### PR TITLE
Fix/odd 751 cancel download

### PR DESCRIPTION
**Pull request by chuanlin2018**
Fixed issue: when user cancelled one zip download, the process didn't kick off the next one.

### CODE REVIEW

**Comment by RayPlante** [comment]
@chuanlin2018, it looks like this branch was not (recently) cloned from usnistgov/integration.  Please do a merge of usnistgov/integration into this fix branch to correct the CI failure.  (Be sure to do a `git fetch usnistgov` first.)

**Comment by chuanlin2018** [comment]
Seems I did it right this time?

**Comment by RayPlante** [comment]
(Note that this PR was prematurely merged.  I'm testing the result on integration.)

I had trouble testing this exact feature; however, it seems the change has not broken anything with regard to bundle downloads, and I can cancel a download.

**Comment by chuanlin2018** [comment]
When you cancel a download, the next available bundle should be kicked off.
Current version does not kick off the next one so if you cancel all
downloads, the process will not move forward.

**Pull request merged**
