### PR TITLE
Fix/odd848 about contact links

### PR DESCRIPTION
**Pull request by chuanlin2018**
http://mml.nist.gov:8080/browse/ODD-848

I made two changes to the header menu bar in this branch:
1. Changed "Home" icon to text "About".
2. Added "Contact" item that pointed to the help page in SDP.

### CODE REVIEW

**Comment by deoyani** [comment]
@chuanlin 
Please update Contact link to 
https://localhost/sdp/#/help/app-contact-us 
as mentioned in ticket. 
Not https://localhost/sdp/#/help

**Comment by chuanlin2018** [comment]
To test this branch in oar-docker, do the following:
1. Check out oar-docker integration13 branch.
2. Update the config file oar-docker/apps/deployment.yml by setting pubpdr tag to fix/ODD848-about-contact-links.

**Comment by chuanlin2018** [comment]
Fixed and tested oar-docker in local. Please test again.

**Comment by RayPlante** [comment]
This PR is being re-merged.   This was originally supposed to be merged to the integration13 branch, but was committed instead to integration.  Since then, the integration branch was deleted and then recreated as a fork of integration13; that is, integration13 is the new integration.  With this, this PR branch will need to merged to this new integration (which I'll do).

**Pull request merged**
