### PR TITLE
ODD-812: Fixed tree table pre-select problem

### PR DESCRIPTION
**Pull request by RayPlante**
This PR deprecates #103 from @chuanlin2018  after I botched an attempt at a rebase.  It addresses JIRA issue, [ODD-812 ("Datacart pop up only pre-select first level")](http://mml.nist.gov:8080/browse/ODD-812).  From the original PR:

> Fixed the problem that only the first level tree table in datacart was checked after user clicks on the download all button.
> 
> Almost all code was changed because I changed indent from 2 spaces to 4.
> 
> The actual changes are the following functions:
> this.buildSelectDataArray(this.dataFiles);
> this.checkNode(this.dataFiles, this.dataArray);

### CODE REVIEW

**Comment by RayPlante** [comment]
@chuanlin2018: Have you/can you test this under oar-docker?  I'm having some trouble getting datacart downloads working.

**Comment by chuanlin2018** [comment]
I tested in local. Will try docker tomorrow.

Thanks.
Chuan

**Comment by chuanlin2018** [comment]
I deployed and ran local docker today. The bundle download worked fine for id 50FF29D41202478EE0531A57068105821843.
I got "Ooops..." error for JANAF ECBCC1C1301D2ED9E04306570681B10735
The log that I added for testing showed:
"No Files added in the Bundle, there are problems accessing URLs."
Seems working but I need to modify the UI to display the proper message.

**Comment by RayPlante** [comment]
The issue I was running into was nginx size limit.  Once fixed, downloads worked

**Pull request merged**
