### PR TITLE
Do not read file level metrics data for landing page

### PR DESCRIPTION
**Pull request by chuanlin2018**
Removed the code that read file level metrics which wasn't used in landing page.

### CODE REVIEW

**Review by RayPlante — CHANGES_REQUESTED** [review]
It looks like one of the angular unit tests is failing.  Run "npm test" to see details; please update.

**Comment by chuanlin2018** [comment]
Checking...

**Comment by chuanlin2018** [comment]
Unit test should be fixed now.

**Review by RayPlante — APPROVED** [review]
Unit tests now pass.  Behavior was tested on testdata (along with #323).

**Pull request merged**
